# Generated by Django 2.2.16 on 2022-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20221112_1824"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_follows",
        ),
    ]
